# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64dbf98c351c8c8118e404e032221d6612216250a1fe3515d76b6789e29e1659d642aa960cb72cb56eaf793497a21d34030d486a117c51e01bd54824e1fba3fc

test:
  secret_key_base: 717f542104dc9aa46fe607341aa0b71cb82395a71d238dc41ef7abfaf904fc30be3b1249ab2bbae4649834df3f547dbf1d068b5b085108928c80b1aaebc3ba45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
